spring:
  application:
    name: demo

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: jdbc:mysql://boonsan-db.czwxpqbngp21.ap-northeast-1.rds.amazonaws.com/boonsan_db?autoReconnect=true # 변경해주세요
    username: admin # 변경해주세요
    password: admin123 # 변경해주세요
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
  sql:
    init:
      platform: mysql

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
