spring:
  application:
    name: demo

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
#    view:
#      prefix: /WEB-INF/views/
#      suffix: .jsp

  datasource:
    url: 
    username: 
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
  sql:
    init:
      platform: mysql

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
